/**:
  ros__parameters:
    imu_r_x: 0.0
    imu_r_y: 0.0
    imu_r_z: 0.0
    imu2lidar_x: -0.6
    imu2lidar_y: -0.52
    imu2lidar_z: -179.32

#    imu_topic: /applanix
#    odom_topic: /applanix
#    lidar_topic: /hesai
#    navsatfix_topic: /applanix

    imu_topic: /applanix/lvx_client/imu_raw
    odom_topic: /applanix/lvx_client/odom
    lidar_topic: /hesai/pandar
    navsatfix_topic: /applanix/lvx_client/gnss/fix
    ins_solution_topic: /applanix/lvx_client/gsof/ins_solution_49

#    imu_topic: /sensing/gnss/clap/ros/imu
#    odom_topic: /sensing/gnss/clap/ros/odometry
#    lidar_topic: /sensing/lidar/top/mirror_cropped/pointcloud_ex
#    navsatfix_topic: /sensing/gnss/clap/ros/gps_nav_sat_fix

    publish_tf: true
    enable_ned2enu: false